ci: extend error information in workflow summary on macos

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,7 +31,8 @@ jobs:
       - name: Build
         # Current encounters errors in civetweb.
         continue-on-error: true
-        run: swift build
+        run: |
+          swift build && exit 0 || echo "::error:: Build step failed"
 
   windows:
     runs-on: windows-latest
